name: build
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
        hazelcast: [ '4.2-SNAPSHOT' ]
        jet: [ '4.4-SNAPSHOT' ]
        architecture: [ 'x64' ]
        distribution: [ 'adopt' ]
    name: Build with JDK ${{ matrix.java }} and Hazelcast ${{ matrix.hazelcast }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
          distribution: ${{ matrix.distribution }}

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -Dhazelcast.version=${{ matrix.hazelcast }} -Dhazelcast.jet.version=${{ matrix.jet }} package -P checkstyle,findbugs
