name: Release version
on:
  push:
    branches:
      - '*'
#  create:
#    - tag

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
        hazelcast: [ '4.2-SNAPSHOT' ]
        jet: [ '4.4-SNAPSHOT' ]
        architecture: [ 'x64' ]
    name: Build with JDK ${{ matrix.java }} and Hazelcast ${{ matrix.hazelcast }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          server-id: snapshot-repository
          server-username: MAVEN_RELEASE_USERNAME
          server-password: MAVEN_RELEASE_PASSWORD
          architecture: ${{ matrix.architecture }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -q deploy -P release
        env:
          MAVEN_RELEASE_USERNAME: ${{ secrets.MAVEN_RELEASE_USERNAME }}
          MAVEN_RELEASE_PASSWORD: ${{ secrets.MAVEN_RELEASE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}